### ISSUE TITLE
Combine boot methods, add a `type`

### ISSUE THREAD

**Issue by ste78** [openflighthpc/metal-server#10]
So now having tried to use this in a more generic way (ie not the way old metalware used to do things) I think I may have been a bit shortsighted when we spec'd only 2 boot types. 

For one, we should be referring to the `uefi` boot type as the `grub` boot type as thats more accurate as to what it is, and secondly my recent experience getting IBM power machines to boot using our stack suggests we should be supporting multiple grub build methods (not just x86_64-UEFI) 

For example if you run on a metalcontroller image the following:
```
yum -y install grub2-efi-x64-modules grub2-ppc64le-modules
grub2-mknetdir --subdir /tmp/hello --net-directory=/tmp/test
```

You end up with 3 different grub network boot environments. In metal world you'd add the correct `core.xxx` command to the dhcp hosts file relative to your tftpboot base path  eg `filename "p9/boot/grub2/powerpc-ieee1275/core.elf";` 

So.... I think we should explore rather than having `uefibootmenu` we have `grubbootmenu` and then allow a number of configurable environments on the server side eg
grubbootmethods:
   x86_64: 
     tftp_system_dir: /var/lib/tftpboot/uefi/
  ppc:
    tftp_system_dir: /var/lib/tftpboot/ppc/
    
then somthing like 

`uefibootmenu create x86_64 <name> <filename>`

**Comment by mjtko** [comment]
Something like this:

1. rename “uefi boot type” entities to “grub boot type” entities
2. allow grub boot type entities to be uploaded with a "type" (or "flavour" or whatever other word you like)
3. type/flavour is used to perform look ups in configuration on the server-side when a "grub" entity is created to dictate:
3a. where this type of grub entity should be written (currently what the `Figaro.env.Uefi_system_dir` value is)
3b. what prefix (if any) should be prepended to the name given for the content (for e.g. `grub.cfg-`)

No need to replace the "PXE/BIOS/legacy" boot type at this time - get lookup table stuff going first; we can look at replacing the other boot type subsequently.

**Comment by ste78** [comment]
```# Configure the system directories for Grub files. Any number of grub types can be
# added following the syntax: Grub_<sub-type>_system_dir. The 'x86' type is required.
Grub_x86_system_dir:      /var/lib/tftpboot/efi```

why is x86 a required field?  also that one would be x86_64 if you're actually referring to the architecture - which I can't get to work - i'm guessing because it has an '_' in it and you are using that as a delimiter? that means I can't get the example I gave in my comment originally (x86_64 and ppc) to happen.
