### ISSUE TITLE
systemd start/stop scripts

### ISSUE THREAD

**Issue by ste78** [openflighthpc/metal-server#7]
Can we make some Redhat systemd start/stop scripts for the server, stored in a /support directory. It's quite a precise process to shut down unicorn cleanly we should be making this as simple as possible (the scripts / systemd modules will need to have configurable application paths). Also if we make these we'll be able to start the server at system boot. 

Ask Stu or Mark if it's not clear what I'm asking for.

**Comment by WilliamMcCumstie** [comment]
I'm not sure if this is this repo is the best location for the `systemd` unit file. As the install path is undefined it is hard to create a unit file that will always work.

However when we build the app into an `rpm` it will have a defined location. So the omnibus `rpm` build recipe will ship with the system file for this location.

**Comment by ste78** [comment]
if tou want to do that it sounds like you need to learn how to make rpms then 😌

i still would have thought an example of a startme stopme script is a sensible thing for any self contained application to have
